services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: messages
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: bar
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@localhost.com
      PGADMIN_DEFAULT_PASSWORD: changeme
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  ui:
    build: 
      context: ./websocket-ui
      dockerfile: Dockerfile
    container_name: websocket-ui
    ports:
      - "3000:3000"
  api:
    build: 
      context: ./websocket-api
      dockerfile: Dockerfile
    container_name: websocket-api
    ports:
      - "8080:80"
    environment:
      - ENVIRONMENT=local
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_NAME=messages
      - DATABASE_USERNAME=foo
      - DATABASE_USERNAME=bar
    depends_on:
      - db
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080


volumes:
  local_pgdata:
  pgadmin-data: